spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: futureSQL
    url: jdbc:postgresql://localhost:5432/pet_projects
  jpa:
    open-in-view: false
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
  mail:
    host: smtp.gmail.com         # SMTP-сервер
    port: 587                      # Порт (обычно 587 для TLS)

    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
app:
  image:
    bucket: C:\MyProjects\NFT_marketplace\backend\token_images
logging:
  level:
    root: info